export const CATEGORIA_LIBROS_LIST_REQUEST = 'CATEGORIA_LIBROS_LIST_REQUEST';
export const CATEGORIA_LIBROS_LIST_SUCCESS = 'CATEGORIA_LIBROS_LIST_SUCCESS';
export const CATEGORIA_LIBROS_LIST_FAIL = 'CATEGORIA_LIBROS_LIST_FAIL';


export const TIPO_OBRA_LIBROS_LIST_REQUEST = 'TIPO_OBRA_LIBROS_LIST_REQUEST';
export const TIPO_OBRA_LIBROS_LIST_SUCCESS = 'TIPO_OBRA_LIBROS_LIST_SUCCESS';
export const TIPO_OBRA_LIBROS_LIST_FAIL = 'TIPO_OBRA_LIBROS_LIST_FAIL';


export const TIPO_MATERIAL_LIBROS_LIST_REQUEST = 'TIPO_MATERIAL_LIBROS_LIST_REQUEST';
export const TIPO_MATERIAL_LIBROS_LIST_SUCCESS = 'TIPO_MATERIAL_LIBROS_LIST_SUCCESS';
export const TIPO_MATERIAL_LIBROS_LIST_FAIL = 'TIPO_MATERIAL_LIBROS_LIST_FAIL';


export const LIBROS_CREATE_REQUEST = 'LIBROS_CREATE_REQUEST';
export const LIBROS_CREATE_SUCCESS = 'LIBROS_CREATE_SUCCESS';
export const LIBROS_CREATE_FAIL = 'LIBROS_CREATE_FAIL';




