export const CRITERIOS_LIST_REQUEST = 'CRITERIOS_LIST_REQUEST';
export const CRITERIOS_LIST_SUCCESS = 'CRITERIOS_LIST_SUCCESS';
export const CRITERIOS_LIST_FAIL = 'CRITERIOS_LIST_FAIL';

export const PROCESO_EVALUACION_LIST_REQUEST = 'PROCESO_EVALUACION_LIST_REQUEST';
export const PROCESO_EVALUACION_LIST_SUCCESS = 'PROCESO_EVALUACION_LIST_SUCCESS';
export const PROCESO_EVALUACION_LIST_FAIL = 'PROCESO_EVALUACION_LIST_FAIL';
