export const DOC_ACREDITACION_CREATE_REQUEST = 'DOC_ACREDITACION_CREATE_REQUEST'
export const DOC_ACREDITACION_CREATE_SUCCESS = 'DOC_ACREDITACION_CREATE_SUCCESS'
export const DOC_ACREDITACION_CREATE_FAIL = 'DOC_ACREDITACION_CREATE_FAIL'


export const DOC_ACREDITACION_FILTER_LIST_REQUEST = 'DOC_ACREDITACION_FILTER_LIST_REQUEST'
export const DOC_ACREDITACION_FILTER_LIST_SUCCESS = 'DOC_ACREDITACION_FILTER_LIST_SUCCESS'
export const DOC_ACREDITACION_FILTER_LIST_FAIL = 'DOC_ACREDITACION_FILTER_LIST_FAIL'


export const DOC_ACREDITACION_LIST_REQUEST = 'DOC_ACREDITACION_LIST_REQUEST'
export const DOC_ACREDITACION_LIST_SUCCESS = 'DOC_ACREDITACION_LIST_SUCCESS'
export const DOC_ACREDITACION_LIST_FAIL = 'DOC_ACREDITACION_LIST_FAIL'




