export const EVIDENCIAS_FILTER_LIST_REQUEST = 'EVIDENCIAS_FILTER_LIST_REQUEST';
export const EVIDENCIAS_FILTER_LIST_SUCCESS = 'EVIDENCIAS_FILTER_LIST_SUCCESS';
export const EVIDENCIAS_FILTER_LIST_FAIL = 'EVIDENCIAS_FILTER_LIST_FAIL';


