export const COOR_CARRERA_LIST_REQUEST = 'COOR_CARRERA_FILTER_LIST_REQUEST';
export const COOR_CARRERA_LIST_SUCCESS = 'COOR_CARRERA_FILTER_LIST_SUCCESS';
export const COOR_CARRERA_LIST_FAIL = 'COOR_CARRERA_FILTER_LIST_FAIL';


export const COOR_INSTITUCIONALES_LIST_REQUEST = 'COOR_INSTITUCIONALES_FILTER_LIST_REQUEST';
export const COOR_INSTITUCIONALES_LIST_SUCCESS = 'COOR_INSTITUCIONALES_FILTER_LIST_SUCCESS';
export const COOR_INSTITUCIONALES_LIST_FAIL = 'COOR_INSTITUCIONALES_FILTER_LIST_FAIL';

export const OTRAS_COMISIONES_LIST_REQUEST = 'OTRAS_COMISIONES_FILTER_LIST_REQUEST';
export const OTRAS_COMISIONES_LIST_SUCCESS = 'OTRAS_COMISIONES_FILTER_LIST_SUCCESS';
export const OTRAS_COMISIONES_LIST_FAIL = 'OTRAS_COMISIONES_FILTER_LIST_FAIL';



