export const INDICADORES_FILTER_LIST_REQUEST = 'INDICADORES_FILTER_LIST_REQUEST';
export const INDICADORES_FILTER_LIST_SUCCESS = 'INDICADORES_FILTER_LIST_SUCCESS';
export const INDICADORES_FILTER_LIST_FAIL = 'INDICADORES_FILTER_LIST_FAIL';

