export const PRUEBAS_LIST_REQUEST = 'PRUEBAS_LIST_REQUEST';
export const PRUEBAS_LIST_SUCCESS = 'PRUEBAS_LIST_SUCCESS';
export const PRUEBAS_LIST_FAIL = 'PRUEBAS_LIST_FAIL';
//export const PRUEBAS_LIST_RESET = 'PRUEBAS_LIST_RESET';

export const PRUEBAS_CREATE_REQUEST = 'PRUEBAS_CREATE_REQUEST'
export const PRUEBAS_CREATE_SUCCESS = 'PRUEBAS_CREATE_SUCCESS'
export const PRUEBAS_CREATE_FAIL = 'PRUEBAS_CREATE_FAIL'





