export const SUBCRITERIOS_FILTER_LIST_REQUEST = 'SUBCRITERIOS_FILTER_LIST_REQUEST';
export const SUBCRITERIOS_FILTER_LIST_SUCCESS = 'SUBCRITERIOS_FILTER_LIST_SUCCESS';
export const SUBCRITERIOS_FILTER_LIST_FAIL = 'SUBCRITERIOS_FILTER_LIST_FAIL';





