


export const DOC_ACREDITACION_DOCENTE_LIST_REQUEST = 'DOC_ACREDITACION_DOCENTE_LIST_REQUEST'
export const DOC_ACREDITACION_DOCENTE_LIST_SUCCESS = 'DOC_ACREDITACION_DOCENTE_LIST_SUCCESS'
export const DOC_ACREDITACION_DOCENTE_LIST_FAIL = 'DOC_ACREDITACION_DOCENTE_LIST_FAIL'


