
export const TIPO_INVENTARIO_LIST_REQUEST = 'TIPO_INVENTARIO_LIST_REQUEST';
export const TIPO_INVENTARIO_LIST_SUCCESS = 'TIPO_INVENTARIO_LIST_SUCCESS';
export const TIPO_INVENTARIO_LIST_FAIL = 'TIPO_INVENTARIO_LIST_FAIL';

export const ESTADO_INVENTARIO_LIST_REQUEST = 'ESTADO_INVENTARIO_LIST_REQUEST';
export const ESTADO_INVENTARIO_LIST_SUCCESS = 'ESTADO_INVENTARIO_LIST_SUCCESS';
export const ESTADO_INVENTARIO_LIST_FAIL = 'ESTADO_INVENTARIO_LIST_FAIL';

export const UBICACION_INVENTARIO_LIST_REQUEST = 'UBICACION_INVENTARIO_LIST_REQUEST';
export const UBICACION_INVENTARIO_LIST_SUCCESS = 'UBICACION_INVENTARIO_LIST_SUCCESS';
export const UBICACION_INVENTARIO_LIST_FAIL = 'UBICACION_INVENTARIO_LIST_FAIL';


export const INVENTARIO_CREATE_REQUEST = 'INVENTARIO_CREATE_REQUEST';
export const INVENTARIO_CREATE_SUCCESS = 'INVENTARIO_CREATE_SUCCESS';
export const INVENTARIO_CREATE_FAIL = 'INVENTARIO_CREATE_FAIL';

export const INVENTARIO_LIST_REQUEST = 'INVENTARIO_LIST_REQUEST';
export const INVENTARIO_LIST_SUCCESS = 'INVENTARIO_LIST_SUCCESS';
export const INVENTARIO_LIST_FAIL = 'INVENTARIO_LIST_FAIL';
